"""Shop address for user

Revision ID: c122a46c4904
Revises: 58c4e943fbd7
Create Date: 2020-02-12 14:12:49.132406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c122a46c4904'
down_revision = '58c4e943fbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_address', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shop_address')
    # ### end Alembic commands ###
